<a href="https://colab.research.google.com/github/padolekrushna/Daily_Data-Science-Python-Practice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

for num in range(1, 11):
    if num == 5:
        continue
    if num == 8:
        break
    print(num)

print("\n")

colors = ["red", "blue", "green"]
colors_copy = colors.copy()

more_colors = ["yellow", "purple", "orange"]
combined_colors = colors + more_colors
print(combined_colors)

print("\n")

# Exercise 1
array1 = list(range(1, 11))
array1[5] = 50
print(array1)

print("\n")


1
2
3
4
6
7


['red', 'blue', 'green', 'yellow', 'purple', 'orange']


[1, 2, 3, 4, 5, 50, 7, 8, 9, 10]




In [ ]:
# Exercise 2
array2 = [1.5, 2.5, 3.5, 4.5]
array2.append(5.5)
array2.remove(3.5)
print(array2)

[1.5, 2.5, 4.5, 5.5]


In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [15]:
arr2=np.array(([1,2,3,4,5],[1,2,3,4,5]))
print(arr2)
arr2

[[1 2 3 4 5]
 [1 2 3 4 5]]


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [14]:
arr3=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(arr3)
arr3

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [16]:
np.sum(arr3)

45

In [17]:
np.mean(arr3)

3.0

In [18]:
np.max(arr3)

5

In [19]:
np.std(arr3)

1.4142135623730951

In [21]:
np.sum(arr3,axis=0) #column wise sum

array([ 3,  6,  9, 12, 15])

In [22]:
np.sum(arr3,axis=1) #roe wise sum

array([15, 15, 15])

In [23]:
np.sum(arr1,axis=0)

15

In [25]:
#np.sum(arr1,axis=1) #error

#assignment

In [26]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
a=np.array(range(1,11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [37]:
np.random.rand(5)

array([0.56913351, 0.63345533, 0.98325572, 0.31794945, 0.35719901])

In [38]:
arr = np.random.randint(1, 100, 5)  # Generates 5 random integers between 1 and 100
print(arr)


[42 29 65 60 54]


In [45]:
arr0 = np.arange(1, 10)
reshaped_arr = arr0.reshape(3, 3)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
transposed_matrix = reshaped_arr.T

print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
